spring:
  application:
    name: finance-app
  thymeleaf:
    cache: false

server:
  port: 8080

finance:
  storage:
    users-file: ${user.home}/.finance-app/data/users.csv
    accounts-file: ${user.home}/.finance-app/data/accounts.csv
  security:
    default-admin-password: admin123
